jobs:
  - name: my-simple-job
    public: true
    plan:
      - task: my-simple-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello World!"]