
jobs:

- name: my-simple-job
  plan:
  - task: my-simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: bash
        args:
        - -euc
        - |
          echo "Hello World!"

