
jobs:

- name: my-simple-job
  plan:
  - get: ubuntu-image
  - get: dotnet-cli-yamilst
  - task: my-simple-task
    file: dotnet-cli-yamilst/examples/simple-pipeline-with-task/tasks/task.yml
    image: ubuntu-image
    inputs: 
      - name: dotnet-cli-yamilst
    params:
      HELLO_WORLD: Hello world!

resources:

- name: dotnet-cli-yamilst
  type: git
  source:
    branch: master
    uri: https://github.com/RealOrko/dotnet-cli-yamlist.git

- name: ubuntu-image
  type: registry-image
  source:
    repository: docker.io/ubuntu

